export const allCardsList = [
  {
    format: 'Vinyl',
    description:
      "'2023 marks the 10th anniversary of Daft Punk's multi Grammy winning hit record 'Random Access Memories', including 'Get Lucky', 'Instant Crush', 'Lose Yourself to Dance' and featuring Pharrell Willams, Nile Rodgers, Julien Casablancas, Paul Williams, Panda Bear and Todd Edwards. This special expanded edition includes 35 minutes of unreleased music (Demo and Studio Outtakes).'",
    price: '75.64',
    artist: 'Daft Punk',
    album: 'Random Access Memories',
    diameter: 12,
    rpm: 33,
    genre: 'Dance',
    style: 'House',
    recordLabel: 'Sony Music CMG',
    weight: 180,
    condition: 'Mint',
    coverCondition: 'Mint',
    images: 'https://i.ebayimg.com/images/g/LHAAAOSwFYNj4~H4/s-l1600.png',
    id: '1',
    releaseYear: 2013,
  },
  {
    format: 'Vinyl',
    description:
      "'Collector's Edition of Radiohead's groundbreaking album 'OK Computer', featuring hits like 'Paranoid Android' and 'Karma Police'. This edition includes exclusive artwork, a booklet, and a bonus disc with unreleased tracks and live recordings.'",
    price: '89.99',
    artist: 'Radiohead',
    album: 'OK Computer',
    diameter: 12,
    rpm: 33,
    genre: 'Alternative',
    style: 'Experimental Rock',
    recordLabel: 'XL Recordings',
    weight: 180,
    condition: 'Near Mint',
    coverCondition: 'Near Mint',
    images: 'https://i.ebayimg.com/images/g/pcsAAOSw1X5keOfc/s-l1600.png',
    id: '2',
    releaseYear: 1997,
  },
  {
    format: 'Vinyl',
    description:
      "'20th Anniversary Edition of Arctic Monkeys' debut album 'Whatever People Say I Am, That's What I'm Not'. Includes the hit singles 'I Bet You Look Good On The Dancefloor' and 'When the Sun Goes Down.'",
    price: '69.95',
    artist: 'Arctic Monkeys',
    album: "Whatever People Say I Am, That's What I'm Not",
    diameter: 12,
    rpm: 33,
    genre: 'Indie Rock',
    style: 'Post-Punk Revival',
    recordLabel: 'Domino',
    weight: 180,
    condition: 'Very Good Plus',
    coverCondition: 'Very Good Plus',
    images: 'https://i.ebayimg.com/images/g/ODkAAOSwisllhUST/s-l1600.jpg',
    id: '3',
    releaseYear: 2006,
  },
  {
    format: 'Vinyl',
    description:
      "'The Beatles' iconic album 'Sgt. Pepper's Lonely Hearts Club Band' in a limited edition reissue. Includes the classic tracks 'Lucy in the Sky with Diamonds' and 'A Day in the Life.'",
    price: '99.99',
    artist: 'The Beatles',
    album: "Sgt. Pepper's Lonely Hearts Club Band",
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Psychedelic Rock',
    recordLabel: 'Parlophone',
    weight: 180,
    condition: 'Mint',
    coverCondition: 'Mint',
    images: 'https://i.ebayimg.com/images/g/oEUAAOSwnillmj3a/s-l1600.jpg',
    id: '4',
    releaseYear: 1967,
  },
  {
    format: 'Vinyl',
    description:
      "'Fleetwood Mac's timeless album 'Rumours' with hits like 'Go Your Own Way' and 'Dreams'. Deluxe edition with bonus tracks and exclusive packaging.'",
    price: '79.50',
    artist: 'Fleetwood Mac',
    album: 'Rumours',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Soft Rock',
    recordLabel: 'Warner Bros. Records',
    weight: 180,
    condition: 'Near Mint',
    coverCondition: 'Near Mint',
    images: 'https://i.ebayimg.com/images/g/VrcAAOSwKytlmA8s/s-l1600.jpg',
    id: '5',
    releaseYear: 1977,
  },
  {
    format: 'Vinyl',
    description:
      "'Led Zeppelin's legendary album 'IV' remastered and reissued on vinyl. Includes timeless classics like 'Stairway to Heaven' and 'Black Dog.'",
    price: '85.00',
    artist: 'Led Zeppelin',
    album: 'IV',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Hard Rock',
    recordLabel: 'Atlantic Records',
    weight: 180,
    condition: 'Very Good',
    coverCondition: 'Very Good',
    images: 'https://i.ebayimg.com/images/g/MgQAAOSwOi9lOlvC/s-l960.jpg',
    id: '6',
    releaseYear: 1971,
  },
  {
    format: 'Vinyl',
    description:
      "'Amy Winehouse's soulful masterpiece 'Back to Black' in a limited edition pressing. Includes hits like 'Rehab' and 'Back to Black.'",
    price: '95.00',
    artist: 'Amy Winehouse',
    album: 'Back to Black',
    diameter: 12,
    rpm: 33,
    genre: 'Soul',
    style: 'Rhythm and Blues',
    recordLabel: 'Universal Republic',
    weight: 180,
    condition: 'Very Good Plus',
    coverCondition: 'Very Good Plus',
    images: 'https://i.ebayimg.com/images/g/pJkAAOSwSWllg6Fe/s-l1600.png',
    id: '7',
    releaseYear: 2006,
  },
  {
    format: 'Vinyl',
    description:
      "'Pink Floyd's classic album 'The Dark Side of the Moon' in a special edition with holographic cover art. A must-have for any vinyl collector.'",
    price: '105.99',
    artist: 'Pink Floyd',
    album: 'The Dark Side of the Moon',
    diameter: 12,
    rpm: 33,
    genre: 'Progressive Rock',
    style: 'Psychedelic Rock',
    recordLabel: 'Harvest',
    weight: 180,
    condition: 'Mint',
    coverCondition: 'Mint',
    images: 'https://i.ebayimg.com/images/g/J0kAAOSwGy1lLjF8/s-l1600.png',
    id: '8',
    releaseYear: 1973,
  },
  {
    format: 'Vinyl',
    description:
      "'David Bowie's groundbreaking album 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars' in a deluxe edition with bonus tracks and exclusive artwork.'",
    price: '88.75',
    artist: 'David Bowie',
    album: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Glam Rock',
    recordLabel: 'RCA Records',
    weight: 180,
    condition: 'Near Mint',
    coverCondition: 'Near Mint',
    images: 'https://i.ebayimg.com/images/g/RpkAAOSwjT9k8JgH/s-l1600.jpg',
    id: '9',
    releaseYear: 1972,
  },
  {
    format: 'Vinyl',
    description:
      "'Nirvana's iconic album 'Nevermind' in a special edition with remastered audio and exclusive packaging. Includes the legendary track 'Smells Like Teen Spirit.'",
    price: '79.99',
    artist: 'Nirvana',
    album: 'Nevermind',
    diameter: 12,
    rpm: 33,
    genre: 'Grunge',
    style: 'Alternative Rock',
    recordLabel: 'DGC Records',
    weight: 180,
    condition: 'Very Good Plus',
    coverCondition: 'Very Good Plus',
    images: 'https://i.ebayimg.com/images/g/TGgAAOSwhcNllJsP/s-l1600.jpg',
    id: '10',
    releaseYear: 1991,
  },
  {
    format: 'Vinyl',
    description:
      "'Queen's timeless album 'A Night at the Opera' in a limited edition gold vinyl pressing. Features the epic 'Bohemian Rhapsody'.'",
    price: '94.50',
    artist: 'Queen',
    album: 'A Night at the Opera',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Classic Rock',
    recordLabel: 'EMI',
    weight: 180,
    condition: 'Mint',
    coverCondition: 'Mint',
    images: 'https://i.ebayimg.com/images/g/AGQAAOSwpHdlfIhW/s-l1600.jpg',
    id: '11',
    releaseYear: 1975,
  },
  {
    format: 'Vinyl',
    description:
      "'Prince's iconic album 'Purple Rain' in a remastered and expanded edition. Includes hits like 'Purple Rain' and 'When Doves Cry.'",
    price: '82.95',
    artist: 'Prince',
    album: 'Purple Rain',
    diameter: 12,
    rpm: 33,
    genre: 'Funk',
    style: 'R&B',
    recordLabel: 'Warner Bros. Records',
    weight: 180,
    condition: 'Near Mint',
    coverCondition: 'Near Mint',
    images: 'https://i.ebayimg.com/images/g/X-IAAOSwVsFhjryd/s-l1600.jpg',
    id: '12',
    releaseYear: 1984,
  },
  {
    format: 'Vinyl',
    description:
      "'The Rolling Stones' classic album 'Exile on Main St.' in a limited edition reissue. Features hits like 'Tumbling Dice' and 'Happy.'",
    price: '98.00',
    artist: 'The Rolling Stones',
    album: 'Exile on Main St.',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Blues Rock',
    recordLabel: 'Rolling Stones Records',
    weight: 180,
    condition: 'Very Good Plus',
    coverCondition: 'Very Good Plus',
    images: 'https://i.ebayimg.com/images/g/C3cAAOSwvgVljeEk/s-l1600.jpg',
    id: '13',
    releaseYear: 1972,
  },
  {
    format: 'Vinyl',
    description:
      "'U2's legendary album 'The Joshua Tree' in a special edition with bonus tracks and exclusive artwork. Includes the hits 'With or Without You' and 'I Still Haven't Found What I'm Looking For.'",
    price: '87.25',
    artist: 'U2',
    album: 'The Joshua Tree',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Alternative Rock',
    recordLabel: 'Island Records',
    weight: 180,
    condition: 'Mint',
    coverCondition: 'Mint',
    images: 'https://i.ebayimg.com/images/g/zxQAAOSwNuhlkvXu/s-l1600.jpg',
    id: '14',
    releaseYear: 1987,
  },
  {
    format: 'Vinyl',
    description:
      "'Bob Dylan's influential album 'Highway 61 Revisited' in a deluxe edition with rare bonus tracks and exclusive liner notes.'",
    price: '91.50',
    artist: 'Bob Dylan',
    album: 'Highway 61 Revisited',
    diameter: 12,
    rpm: 33,
    genre: 'Folk',
    style: 'Blues',
    recordLabel: 'Columbia Records',
    weight: 180,
    condition: 'Near Mint',
    coverCondition: 'Near Mint',
    images: 'https://i.ebayimg.com/images/g/lB8AAOSwhIhlkGs5/s-l1600.jpg',
    id: '15',
    releaseYear: 1965,
  },
  {
    format: 'Vinyl',
    description:
      "'Michael Jackson's iconic album 'Thriller' in a special edition picture disc. Includes hits like 'Billie Jean' and 'Beat It.'",
    price: '105.99',
    artist: 'Michael Jackson',
    album: 'Thriller',
    diameter: 12,
    rpm: 33,
    genre: 'Pop',
    style: 'R&B',
    recordLabel: 'Epic Records',
    weight: 180,
    condition: 'Mint',
    coverCondition: 'Mint',
    images: 'https://i.ebayimg.com/images/g/u1EAAOSwuxFY2G5O/s-l960.jpg',
    id: '16',
    releaseYear: 1982,
  },
  {
    format: 'Vinyl',
    description:
      "'The Who's classic rock opera 'Tommy' in a limited edition colored vinyl pressing. Features the iconic tracks 'Pinball Wizard' and 'See Me, Feel Me.'",
    price: '88.75',
    artist: 'The Who',
    album: 'Tommy',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Hard Rock',
    recordLabel: 'Polydor',
    weight: 180,
    condition: 'Very Good Plus',
    coverCondition: 'Very Good Plus',
    images: 'https://i.ebayimg.com/images/g/SBoAAOSwijNlVlnJ/s-l1600.jpg',
    id: '17',
    releaseYear: 1969,
  },
  {
    format: 'Vinyl',
    description:
      "'Kanye West's groundbreaking album 'My Beautiful Dark Twisted Fantasy' in a deluxe edition with alternate artwork and bonus tracks.'",
    price: '99.50',
    artist: 'Kanye West',
    album: 'My Beautiful Dark Twisted Fantasy',
    diameter: 12,
    rpm: 33,
    genre: 'Hip Hop',
    style: 'Experimental',
    recordLabel: 'Def Jam Recordings',
    weight: 180,
    condition: 'Near Mint',
    coverCondition: 'Near Mint',
    images: 'https://i.ebayimg.com/images/g/Za8AAOSwW1ZlPlG7/s-l1600.jpg',
    id: '18',
    releaseYear: 2010,
  },
  {
    format: 'Vinyl',
    description:
      "'Bruce Springsteen's iconic album 'Born to Run' in a remastered and expanded edition. Includes hits like 'Born to Run' and 'Thunder Road.'",
    price: '96.00',
    artist: 'Bruce Springsteen',
    album: 'Born to Run',
    diameter: 12,
    rpm: 33,
    genre: 'Rock',
    style: 'Heartland Rock',
    recordLabel: 'Columbia Records',
    weight: 180,
    condition: 'Mint',
    coverCondition: 'Mint',
    images: 'https://i.ebayimg.com/images/g/kAsAAOSwdB1lmjHM/s-l1600.jpg',
    id: '19',
    releaseYear: 1975,
  },
];
